name: CI Pipeline

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

  analysis:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Cache SonarQube scanner
        uses: actions/cache@v4
        with:
          path: ~/.sonar/native-sonar-scanner
          key: sonar-scanner-cache

      - name: Count lines of code with Cloc
        run: |
          sudo apt-get install -y cloc
          cloc src/ > cloc-report.txt
          cat cloc-report.txt

      - name: Upload LOC report
        uses: actions/upload-artifact@v4
        with:
          name: loc-report
          path: cloc-report.txt

      - name: Run SonarQube analysis
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=bohdanHavry_lb6
            -Dsonar.organization=bohdanhavry
            -Dsonar.sources=src
            -Dsonar.host.url=https://sonarcloud.io

      - name: Run ESLint via Reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: error

  review-check:
    if: github.event_name == 'pull_request' && github.base_ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Перевірка наявності схваленого код-рев’ю
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });

            const approved = reviews.data.some(review => review.state === 'APPROVED');
            if (!approved) {
              core.setFailed("❌ Код-рев’ю не схвалено. Потрібне хоча б одне APPROVED рев’ю.");
            } else {
              console.log("✅ Є хоча б одне схвалене код-рев’ю.");
            }

  check-develop-changes:
    if: github.event_name == 'pull_request' && github.base_ref == 'develop'
    runs-on: ubuntu-latest
    needs: [review-check]
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0

      - name: Pull latest changes and log commits
        run: |
          git pull origin develop
          git log --oneline --graph > develop_changes.txt
          cat develop_changes.txt
      - name: Upload develop branch changes
        uses: actions/upload-artifact@v4
        with:
          name: develop-changes
          path: develop_changes.txt
